apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: three-tier
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 3500
      targetPort: 3500
      nodePort: 32080   # Choose a nodePort (e.g., 32080) that is not in use and accessible
  type: NodePort

