apiVersion: v1
kind: Service
metadata: 
  name: frontend
  namespace: three-tier
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32081   # Choose a nodePort (e.g., 32081) that is not in use and accessible
  type: NodePort   # Change type from ClusterIP to NodePort

